--1.
CREATE TABLE T_ITEM_LIST(
    NO          NUMBER( 6 )PRIMARY KEY,
    ITEM_NAME   VARCHAR2( 24 )NOT NULL,
    PRICE       NUMBER( 6 ),
    CREATE_DATE DATE DEFAULT SYSDATE
);


--2.
CREATE SEQUENCE T_ITEM_LIST_PK_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999 NOCYCLE;


--3.
SELECT T_ITEM_LIST_PK_SEQ.NEXTVAL
FROM DUAL;


--4.
INSERT INTO T_ITEM_LIST(
    NO,
    ITEM_NAME,
    PRICE
)VALUES( T_ITEM_LIST_PK_SEQ.NEXTVAL,
         'name',
         10000 );

SELECT *
FROM T_ITEM_LIST;